"""add category column to game

Revision ID: 36d3e40a5f74
Revises: 4ba84043d320
Create Date: 2025-11-21 20:49:28.958382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36d3e40a5f74"
down_revision: Union[str, Sequence[str], None] = "4ba84043d320"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("category", sa.String(length=50), nullable=True))

    op.execute("UPDATE games SET category = 'RTS' WHERE category IS NULL")
    op.alter_column("games", "category", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "category")
    # ### end Alembic commands ###
