"""add title and content fields to announcement

Revision ID: 008606da9cc5
Revises: c81c03cadde7
Create Date: 2025-10-07 20:49:25.972615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "008606da9cc5"
down_revision: Union[str, Sequence[str], None] = "c81c03cadde7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements",
        sa.Column("title", sa.String(length=100), nullable=False),
    )
    op.add_column("announcements", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("announcements", "content")
    op.drop_column("announcements", "title")
    # ### end Alembic commands ###
