"""add image url to games and announcements

Revision ID: d8bb87b6d199
Revises: 008606da9cc5
Create Date: 2025-10-09 18:56:53.526067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8bb87b6d199"
down_revision: Union[str, Sequence[str], None] = "008606da9cc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements",
        sa.Column("image_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "games", sa.Column("image_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "image_url")
    op.drop_column("announcements", "image_url")
    # ### end Alembic commands ###
