"""add new avatar fields for users

Revision ID: d086e319d9c3
Revises: ea2228eec1c2
Create Date: 2026-04-08 16:12:40.375710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d086e319d9c3"
down_revision: Union[str, Sequence[str], None] = "ea2228eec1c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("users", sa.Column("avatar_icon_id", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("avatar_color", sa.String(length=7), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_color")
    op.drop_column("users", "avatar_icon_id")
    # ### end Alembic commands ###
